var math = 75.25;
var biology = 65;
var chemistry = 80;
var physics = 35.45;
var bangla = 99.50;
var totalMarks = math + biology + chemistry + physics + bangla;
var totalSubjects = 5;
var averageMarks = totalMarks / totalSubjects;
averageMarks = averageMarks.toFixed(2);
averageMarks = parseFloat(averageMarks);
console.log(averageMarks);
